name: CI

on:
  push:

jobs:
  biome:
    name: Biome (${{ matrix.workspace }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ["frontend", "backend"]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun x biome check ${{ matrix.workspace }}

  knip:
    name: Knip (${{ matrix.workspace }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ["frontend", "backend"]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun x knip --workspace ${{ matrix.workspace }}

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ["frontend", "backend"]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: cd ${{ matrix.workspace }} && bun run build
